services:
  maloja:
    build:
      context: .
      dockerfile: Containerfile
      args:
        - CARGO_PROFILE=dev
    volumes:
      - ./testdata/state:/data
      - ./testdata/config:/config:ro
      - ./testdata/logs:/logs
    ports:
      - "42010:42010"
    stdin_open: true
    tty: true
    env_file:
      - .env.dev
