services:
  maloja:
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - ./testdata/state:/data
      - ./testdata/config:/config:ro
      - ./testdata/logs:/var/log/maloja
    ports:
      - "42010:42010"
    stdin_open: true
    tty: true
    command: "/bin/maloja-rs"
    env_file:
      - .env.dev
    environment:
      - MALOJA_CONFIG_PATH=/config
      - MALOJA_DATA_PATH=/data
